### ISSUE TITLE
Move development packages to “devDependencies”

### ISSUE THREAD

**Issue by yvt** [melounek/switch-css-transition-group#1]
https://github.com/melounek/switch-css-transition-group/blob/master/package.json#L38:
```
  "dependencies": {
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    ...
    "webpack": "^3.8.1”
  }
```

`babel-preset-es2015`, `babel-preset-stage-2`, and `webpack` are development dependencies and therefore should be moved to `devDependencies`.

**Comment by melounek** [comment]
Thanks, dependencies was moved (v0.2.2.)
